name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude='.git*' --exclude='.github'
          path: ./
          remote_path: /home/u851634631/domains/danielhernandezhaygood.com/public_html/
          remote_host: 82.180.174.23
          remote_port: 65002
          remote_user: u851634631
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
